// Generated by scripts/generate-node-block-catalog.ts. Do not edit manually.
import type { NodeMaterialBlock } from "./node-block-loader.js";

/** Lazily loaded AddBlock implementation. */
export const nodeAddBlock: NodeMaterialBlock = { className: "AddBlock", _load: async () => (await import("./blocks/add-block.js")).emitter };
/** Lazily loaded AmbientOcclusionBlock implementation. */
export const nodeAmbientOcclusionBlock: NodeMaterialBlock = {
    className: "AmbientOcclusionBlock",
    _load: async () => (await import("./blocks/ambient-occlusion-block.js")).emitter,
};
/** Lazily loaded AnisotropyBlock implementation. */
export const nodeAnisotropyBlock: NodeMaterialBlock = { className: "AnisotropyBlock", _load: async () => (await import("./blocks/anisotropy-block.js")).emitter };
/** Lazily loaded ArcTan2Block implementation. */
export const nodeArcTan2Block: NodeMaterialBlock = { className: "ArcTan2Block", _load: async () => (await import("./blocks/arc-tan2-block.js")).emitter };
/** Lazily loaded BiPlanarBlock implementation. */
export const nodeBiPlanarBlock: NodeMaterialBlock = { className: "BiPlanarBlock", _load: async () => (await import("./blocks/biplanar-block.js")).emitter };
/** Lazily loaded BonesBlock implementation. */
export const nodeBonesBlock: NodeMaterialBlock = { className: "BonesBlock", _load: async () => (await import("./blocks/bones-block.js")).emitter };
/** Lazily loaded ClampBlock implementation. */
export const nodeClampBlock: NodeMaterialBlock = { className: "ClampBlock", _load: async () => (await import("./blocks/clamp-block.js")).emitter };
/** Lazily loaded ClearCoatBlock implementation. */
export const nodeClearCoatBlock: NodeMaterialBlock = { className: "ClearCoatBlock", _load: async () => (await import("./blocks/clearcoat-block.js")).emitter };
/** Lazily loaded ClipPlanesBlock implementation. */
export const nodeClipPlanesBlock: NodeMaterialBlock = { className: "ClipPlanesBlock", _load: async () => (await import("./blocks/clip-planes-block.js")).emitter };
/** Lazily loaded CloudBlock implementation. */
export const nodeCloudBlock: NodeMaterialBlock = { className: "CloudBlock", _load: async () => (await import("./blocks/cloud-block.js")).emitter };
/** Lazily loaded ColorConverterBlock implementation. */
export const nodeColorConverterBlock: NodeMaterialBlock = { className: "ColorConverterBlock", _load: async () => (await import("./blocks/color-converter-block.js")).emitter };
/** Lazily loaded ColorMergerBlock implementation. */
export const nodeColorMergerBlock: NodeMaterialBlock = { className: "ColorMergerBlock", _load: async () => (await import("./blocks/color-merger.js")).emitter };
/** Lazily loaded ColorSplitterBlock implementation. */
export const nodeColorSplitterBlock: NodeMaterialBlock = { className: "ColorSplitterBlock", _load: async () => (await import("./blocks/color-splitter.js")).emitter };
/** Lazily loaded ConditionalBlock implementation. */
export const nodeConditionalBlock: NodeMaterialBlock = { className: "ConditionalBlock", _load: async () => (await import("./blocks/conditional-block.js")).emitter };
/** Lazily loaded CrossBlock implementation. */
export const nodeCrossBlock: NodeMaterialBlock = { className: "CrossBlock", _load: async () => (await import("./blocks/cross-block.js")).emitter };
/** Lazily loaded CurveBlock implementation. */
export const nodeCurveBlock: NodeMaterialBlock = { className: "CurveBlock", _load: async () => (await import("./blocks/curve-block.js")).emitter };
/** Lazily loaded DerivativeBlock implementation. */
export const nodeDerivativeBlock: NodeMaterialBlock = { className: "DerivativeBlock", _load: async () => (await import("./blocks/derivative-block.js")).emitter };
/** Lazily loaded DesaturateBlock implementation. */
export const nodeDesaturateBlock: NodeMaterialBlock = { className: "DesaturateBlock", _load: async () => (await import("./blocks/desaturate-block.js")).emitter };
/** Lazily loaded DiscardBlock implementation. */
export const nodeDiscardBlock: NodeMaterialBlock = { className: "DiscardBlock", _load: async () => (await import("./blocks/discard-block.js")).emitter };
/** Lazily loaded DistanceBlock implementation. */
export const nodeDistanceBlock: NodeMaterialBlock = { className: "DistanceBlock", _load: async () => (await import("./blocks/distance-block.js")).emitter };
/** Lazily loaded DivideBlock implementation. */
export const nodeDivideBlock: NodeMaterialBlock = { className: "DivideBlock", _load: async () => (await import("./blocks/divide-block.js")).emitter };
/** Lazily loaded DotBlock implementation. */
export const nodeDotBlock: NodeMaterialBlock = { className: "DotBlock", _load: async () => (await import("./blocks/dot-block.js")).emitter };
/** Lazily loaded ElbowBlock implementation. */
export const nodeElbowBlock: NodeMaterialBlock = { className: "ElbowBlock", _load: async () => (await import("./blocks/elbow-block.js")).emitter };
/** Lazily loaded FogBlock implementation. */
export const nodeFogBlock: NodeMaterialBlock = { className: "FogBlock", _load: async () => (await import("./blocks/fog-block.js")).emitter };
/** Lazily loaded FragCoordBlock implementation. */
export const nodeFragCoordBlock: NodeMaterialBlock = { className: "FragCoordBlock", _load: async () => (await import("./blocks/frag-coord-block.js")).emitter };
/** Lazily loaded FragDepthBlock implementation. */
export const nodeFragDepthBlock: NodeMaterialBlock = { className: "FragDepthBlock", _load: async () => (await import("./blocks/frag-depth-block.js")).emitter };
/** Lazily loaded FragmentOutputBlock implementation. */
export const nodeFragmentOutputBlock: NodeMaterialBlock = { className: "FragmentOutputBlock", _load: async () => (await import("./blocks/fragment-output.js")).emitter };
/** Lazily loaded FresnelBlock implementation. */
export const nodeFresnelBlock: NodeMaterialBlock = { className: "FresnelBlock", _load: async () => (await import("./blocks/fresnel-block.js")).emitter };
/** Lazily loaded FrontFacingBlock implementation. */
export const nodeFrontFacingBlock: NodeMaterialBlock = { className: "FrontFacingBlock", _load: async () => (await import("./blocks/front-facing.js")).emitter };
/** Lazily loaded GeometryTextureOutputBlock implementation. */
export const nodeGeometryTextureOutputBlock: NodeMaterialBlock = {
    className: "GeometryTextureOutputBlock",
    _load: async () => (await import("./blocks/geometry-texture-output.js")).emitter,
};
/** Lazily loaded GradientBlock implementation. */
export const nodeGradientBlock: NodeMaterialBlock = { className: "GradientBlock", _load: async () => (await import("./blocks/gradient-block.js")).emitter };
/** Lazily loaded HeightToNormalBlock implementation. */
export const nodeHeightToNormalBlock: NodeMaterialBlock = { className: "HeightToNormalBlock", _load: async () => (await import("./blocks/height-to-normal-block.js")).emitter };
/** Lazily loaded ImageProcessingBlock implementation. */
export const nodeImageProcessingBlock: NodeMaterialBlock = { className: "ImageProcessingBlock", _load: async () => (await import("./blocks/image-processing-block.js")).emitter };
/** Lazily loaded ImageSourceBlock implementation. */
export const nodeImageSourceBlock: NodeMaterialBlock = { className: "ImageSourceBlock", _load: async () => (await import("./blocks/image-source.js")).emitter };
/** Lazily loaded InputBlock implementation. */
export const nodeInputBlock: NodeMaterialBlock = { className: "InputBlock", _load: async () => (await import("./blocks/input-block.js")).emitter };
/** Lazily loaded InstancesBlock implementation. */
export const nodeInstancesBlock: NodeMaterialBlock = { className: "InstancesBlock", _load: async () => (await import("./blocks/instances-block.js")).emitter };
/** Lazily loaded IridescenceBlock implementation. */
export const nodeIridescenceBlock: NodeMaterialBlock = { className: "IridescenceBlock", _load: async () => (await import("./blocks/iridescence-block.js")).emitter };
/** Lazily loaded LengthBlock implementation. */
export const nodeLengthBlock: NodeMaterialBlock = { className: "LengthBlock", _load: async () => (await import("./blocks/length-block.js")).emitter };
/** Lazily loaded LerpBlock implementation. */
export const nodeLerpBlock: NodeMaterialBlock = { className: "LerpBlock", _load: async () => (await import("./blocks/lerp-block.js")).emitter };
/** Lazily loaded LightBlock implementation. */
export const nodeLightBlock: NodeMaterialBlock = { className: "LightBlock", _load: async () => (await import("./blocks/light-block.js")).emitter };
/** Lazily loaded LightInformationBlock implementation. */
export const nodeLightInformationBlock: NodeMaterialBlock = { className: "LightInformationBlock", _load: async () => (await import("./blocks/light-information.js")).emitter };
/** Lazily loaded LoopBlock implementation. */
export const nodeLoopBlock: NodeMaterialBlock = { className: "LoopBlock", _load: async () => (await import("./blocks/loop-block.js")).emitter };
/** Lazily loaded MatrixBuilder implementation. */
export const nodeMatrixBuilder: NodeMaterialBlock = { className: "MatrixBuilder", _load: async () => (await import("./blocks/matrix-blocks.js")).emitter };
/** Lazily loaded MatrixDeterminantBlock implementation. */
export const nodeMatrixDeterminantBlock: NodeMaterialBlock = { className: "MatrixDeterminantBlock", _load: async () => (await import("./blocks/matrix-blocks.js")).emitter };
/** Lazily loaded MatrixSplitterBlock implementation. */
export const nodeMatrixSplitterBlock: NodeMaterialBlock = { className: "MatrixSplitterBlock", _load: async () => (await import("./blocks/matrix-blocks.js")).emitter };
/** Lazily loaded MatrixTransposeBlock implementation. */
export const nodeMatrixTransposeBlock: NodeMaterialBlock = { className: "MatrixTransposeBlock", _load: async () => (await import("./blocks/matrix-blocks.js")).emitter };
/** Lazily loaded MaxBlock implementation. */
export const nodeMaxBlock: NodeMaterialBlock = { className: "MaxBlock", _load: async () => (await import("./blocks/max-block.js")).emitter };
/** Lazily loaded MeshAttributeExistsBlock implementation. */
export const nodeMeshAttributeExistsBlock: NodeMaterialBlock = {
    className: "MeshAttributeExistsBlock",
    _load: async () => (await import("./blocks/mesh-attribute-exists-block.js")).emitter,
};
/** Lazily loaded MinBlock implementation. */
export const nodeMinBlock: NodeMaterialBlock = { className: "MinBlock", _load: async () => (await import("./blocks/min-block.js")).emitter };
/** Lazily loaded ModBlock implementation. */
export const nodeModBlock: NodeMaterialBlock = { className: "ModBlock", _load: async () => (await import("./blocks/mod-block.js")).emitter };
/** Lazily loaded MorphTargetsBlock implementation. */
export const nodeMorphTargetsBlock: NodeMaterialBlock = { className: "MorphTargetsBlock", _load: async () => (await import("./blocks/morph-targets.js")).emitter };
/** Lazily loaded MultiplyBlock implementation. */
export const nodeMultiplyBlock: NodeMaterialBlock = { className: "MultiplyBlock", _load: async () => (await import("./blocks/multiply-block.js")).emitter };
/** Lazily loaded NegateBlock implementation. */
export const nodeNegateBlock: NodeMaterialBlock = { className: "NegateBlock", _load: async () => (await import("./blocks/negate-block.js")).emitter };
/** Lazily loaded NLerpBlock implementation. */
export const nodeNLerpBlock: NodeMaterialBlock = { className: "NLerpBlock", _load: async () => (await import("./blocks/nlerp-block.js")).emitter };
/** Lazily loaded NodeMaterialDebugBlock implementation. */
export const nodeDebugBlock: NodeMaterialBlock = { className: "NodeMaterialDebugBlock", _load: async () => (await import("./blocks/debug-block.js")).emitter };
/** Lazily loaded NodeMaterialTeleportInBlock implementation. */
export const nodeTeleportInBlock: NodeMaterialBlock = { className: "NodeMaterialTeleportInBlock", _load: async () => (await import("./blocks/teleport-in-block.js")).emitter };
/** Lazily loaded NodeMaterialTeleportOutBlock implementation. */
export const nodeTeleportOutBlock: NodeMaterialBlock = { className: "NodeMaterialTeleportOutBlock", _load: async () => (await import("./blocks/teleport-out-block.js")).emitter };
/** Lazily loaded NormalBlendBlock implementation. */
export const nodeNormalBlendBlock: NodeMaterialBlock = { className: "NormalBlendBlock", _load: async () => (await import("./blocks/normal-blend-block.js")).emitter };
/** Lazily loaded NormalizeBlock implementation. */
export const nodeNormalizeBlock: NodeMaterialBlock = { className: "NormalizeBlock", _load: async () => (await import("./blocks/normalize-block.js")).emitter };
/** Lazily loaded OneMinusBlock implementation. */
export const nodeOneMinusBlock: NodeMaterialBlock = { className: "OneMinusBlock", _load: async () => (await import("./blocks/oneminus-block.js")).emitter };
/** Lazily loaded OppositeBlock implementation. */
export const nodeOppositeBlock: NodeMaterialBlock = { className: "OppositeBlock", _load: async () => (await import("./blocks/opposite-block.js")).emitter };
/** Lazily loaded PannerBlock implementation. */
export const nodePannerBlock: NodeMaterialBlock = { className: "PannerBlock", _load: async () => (await import("./blocks/panner-block.js")).emitter };
/** Lazily loaded PBRMetallicRoughnessBlock implementation. */
export const nodePbrMetallicRoughnessBlock: NodeMaterialBlock = {
    className: "PBRMetallicRoughnessBlock",
    _load: async () => (await import("./blocks/pbr-metallic-roughness-block.js")).emitter,
};
/** Lazily loaded PBRMetallicRoughnessBlock__full implementation. */
export const nodePbrMetallicRoughnessBlockFull: NodeMaterialBlock = {
    className: "PBRMetallicRoughnessBlock",
    _load: async () => (await import("./blocks/pbr-metallic-roughness-block-full.js")).emitter,
};
/** Lazily loaded PerturbNormalBlock implementation. */
export const nodePerturbNormalBlock: NodeMaterialBlock = { className: "PerturbNormalBlock", _load: async () => (await import("./blocks/perturb-normal.js")).emitter };
/** Lazily loaded PosterizeBlock implementation. */
export const nodePosterizeBlock: NodeMaterialBlock = { className: "PosterizeBlock", _load: async () => (await import("./blocks/posterize-block.js")).emitter };
/** Lazily loaded PowBlock implementation. */
export const nodePowBlock: NodeMaterialBlock = { className: "PowBlock", _load: async () => (await import("./blocks/pow-block.js")).emitter };
/** Lazily loaded RandomNumberBlock implementation. */
export const nodeRandomNumberBlock: NodeMaterialBlock = { className: "RandomNumberBlock", _load: async () => (await import("./blocks/random-number-block.js")).emitter };
/** Lazily loaded ReciprocalBlock implementation. */
export const nodeReciprocalBlock: NodeMaterialBlock = { className: "ReciprocalBlock", _load: async () => (await import("./blocks/reciprocal-block.js")).emitter };
/** Lazily loaded ReflectBlock implementation. */
export const nodeReflectBlock: NodeMaterialBlock = { className: "ReflectBlock", _load: async () => (await import("./blocks/reflect-block.js")).emitter };
/** Lazily loaded ReflectionBlock implementation. */
export const nodeReflectionBlock: NodeMaterialBlock = { className: "ReflectionBlock", _load: async () => (await import("./blocks/reflection-block.js")).emitter };
/** Lazily loaded ReflectionTextureBaseBlock implementation. */
export const nodeReflectionTextureBaseBlock: NodeMaterialBlock = {
    className: "ReflectionTextureBaseBlock",
    _load: async () => (await import("./blocks/reflection-texture-base-block.js")).emitter,
};
/** Lazily loaded ReflectionTextureBlock implementation. */
export const nodeReflectionTextureBlock: NodeMaterialBlock = {
    className: "ReflectionTextureBlock",
    _load: async () => (await import("./blocks/reflection-texture-block.js")).emitter,
};
/** Lazily loaded RefractBlock implementation. */
export const nodeRefractBlock: NodeMaterialBlock = { className: "RefractBlock", _load: async () => (await import("./blocks/refract-block.js")).emitter };
/** Lazily loaded RefractionBlock implementation. */
export const nodeRefractionBlock: NodeMaterialBlock = { className: "RefractionBlock", _load: async () => (await import("./blocks/refraction-block.js")).emitter };
/** Lazily loaded RemapBlock implementation. */
export const nodeRemapBlock: NodeMaterialBlock = { className: "RemapBlock", _load: async () => (await import("./blocks/remap-block.js")).emitter };
/** Lazily loaded ReplaceColorBlock implementation. */
export const nodeReplaceColorBlock: NodeMaterialBlock = { className: "ReplaceColorBlock", _load: async () => (await import("./blocks/replace-color-block.js")).emitter };
/** Lazily loaded Rotate2dBlock implementation. */
export const nodeRotate2dBlock: NodeMaterialBlock = { className: "Rotate2dBlock", _load: async () => (await import("./blocks/rotate2d-block.js")).emitter };
/** Lazily loaded ScaleBlock implementation. */
export const nodeScaleBlock: NodeMaterialBlock = { className: "ScaleBlock", _load: async () => (await import("./blocks/scale-block.js")).emitter };
/** Lazily loaded ScreenSizeBlock implementation. */
export const nodeScreenSizeBlock: NodeMaterialBlock = { className: "ScreenSizeBlock", _load: async () => (await import("./blocks/screen-size-block.js")).emitter };
/** Lazily loaded ScreenSpaceBlock implementation. */
export const nodeScreenSpaceBlock: NodeMaterialBlock = { className: "ScreenSpaceBlock", _load: async () => (await import("./blocks/screen-space-block.js")).emitter };
/** Lazily loaded ShadowMapBlock implementation. */
export const nodeShadowMapBlock: NodeMaterialBlock = { className: "ShadowMapBlock", _load: async () => (await import("./blocks/shadow-map.js")).emitter };
/** Lazily loaded SheenBlock implementation. */
export const nodeSheenBlock: NodeMaterialBlock = { className: "SheenBlock", _load: async () => (await import("./blocks/sheen-block.js")).emitter };
/** Lazily loaded SimplexPerlin3DBlock implementation. */
export const nodeSimplexPerlin3DBlock: NodeMaterialBlock = { className: "SimplexPerlin3DBlock", _load: async () => (await import("./blocks/simplex-perlin-3d-block.js")).emitter };
/** Lazily loaded SmoothStepBlock implementation. */
export const nodeSmoothStepBlock: NodeMaterialBlock = { className: "SmoothStepBlock", _load: async () => (await import("./blocks/smoothstep-block.js")).emitter };
/** Lazily loaded StepBlock implementation. */
export const nodeStepBlock: NodeMaterialBlock = { className: "StepBlock", _load: async () => (await import("./blocks/step-block.js")).emitter };
/** Lazily loaded StorageReadBlock implementation. */
export const nodeStorageReadBlock: NodeMaterialBlock = { className: "StorageReadBlock", _load: async () => (await import("./blocks/storage-read-block.js")).emitter };
/** Lazily loaded StorageWriteBlock implementation. */
export const nodeStorageWriteBlock: NodeMaterialBlock = { className: "StorageWriteBlock", _load: async () => (await import("./blocks/storage-write-block.js")).emitter };
/** Lazily loaded SubSurfaceBlock implementation. */
export const nodeSubSurfaceBlock: NodeMaterialBlock = { className: "SubSurfaceBlock", _load: async () => (await import("./blocks/subsurface-block.js")).emitter };
/** Lazily loaded SubtractBlock implementation. */
export const nodeSubtractBlock: NodeMaterialBlock = { className: "SubtractBlock", _load: async () => (await import("./blocks/subtract-block.js")).emitter };
/** Lazily loaded TBNBlock implementation. */
export const nodeTBNBlock: NodeMaterialBlock = { className: "TBNBlock", _load: async () => (await import("./blocks/tbn-block.js")).emitter };
/** Lazily loaded TextureBlock implementation. */
export const nodeTextureBlock: NodeMaterialBlock = { className: "TextureBlock", _load: async () => (await import("./blocks/texture-block.js")).emitter };
/** Lazily loaded TransformBlock implementation. */
export const nodeTransformBlock: NodeMaterialBlock = { className: "TransformBlock", _load: async () => (await import("./blocks/transform-block.js")).emitter };
/** Lazily loaded TrigonometryBlock implementation. */
export const nodeTrigonometryBlock: NodeMaterialBlock = { className: "TrigonometryBlock", _load: async () => (await import("./blocks/trigonometry-block.js")).emitter };
/** Lazily loaded TriPlanarBlock implementation. */
export const nodeTriPlanarBlock: NodeMaterialBlock = { className: "TriPlanarBlock", _load: async () => (await import("./blocks/triplanar-block.js")).emitter };
/** Lazily loaded TwirlBlock implementation. */
export const nodeTwirlBlock: NodeMaterialBlock = { className: "TwirlBlock", _load: async () => (await import("./blocks/twirl-block.js")).emitter };
/** Lazily loaded VectorMergerBlock implementation. */
export const nodeVectorMergerBlock: NodeMaterialBlock = { className: "VectorMergerBlock", _load: async () => (await import("./blocks/vector-merger.js")).emitter };
/** Lazily loaded VectorSplitterBlock implementation. */
export const nodeVectorSplitterBlock: NodeMaterialBlock = { className: "VectorSplitterBlock", _load: async () => (await import("./blocks/vector-splitter.js")).emitter };
/** Lazily loaded VertexOutputBlock implementation. */
export const nodeVertexOutputBlock: NodeMaterialBlock = { className: "VertexOutputBlock", _load: async () => (await import("./blocks/vertex-output.js")).emitter };
/** Lazily loaded ViewDirectionBlock implementation. */
export const nodeViewDirectionBlock: NodeMaterialBlock = { className: "ViewDirectionBlock", _load: async () => (await import("./blocks/view-direction.js")).emitter };
/** Lazily loaded VoronoiNoiseBlock implementation. */
export const nodeVoronoiNoiseBlock: NodeMaterialBlock = { className: "VoronoiNoiseBlock", _load: async () => (await import("./blocks/voronoi-noise-block.js")).emitter };
/** Lazily loaded WaveBlock implementation. */
export const nodeWaveBlock: NodeMaterialBlock = { className: "WaveBlock", _load: async () => (await import("./blocks/wave-block.js")).emitter };
/** Lazily loaded WorleyNoise3DBlock implementation. */
export const nodeWorleyNoise3DBlock: NodeMaterialBlock = { className: "WorleyNoise3DBlock", _load: async () => (await import("./blocks/worley-noise-3d-block.js")).emitter };
