import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { format, resolveConfig } from "prettier";
import { loadGraphEmitters } from "../packages/babylon-lite/src/material/node/node-emitter.js";
import { parseNodeMaterialSource } from "../packages/babylon-lite/src/material/node/node-parser.js";
import * as catalog from "../packages/babylon-lite/src/material/node/node-blocks.js";
import { isIgnoredScenePayloadModule } from "./bundle-size-accounting.js";

/** Generate a counted, root-import-only loader for a fixed serialized graph. */
export async function generateNodeMaterialLoader(source: unknown, packageName = "@babylonjs/lite"): Promise<string> {
    const graph = parseNodeMaterialSource(source);
    // Geometry has an opt-in registry entry; all other choices, including the
    // core/full PBR decision, come from the existing default loader.
    const blocks = new Map([...graph.blocks].filter(([, block]) => block.className !== "GeometryTextureOutputBlock"));
    const emitters = await loadGraphEmitters({ ...graph, blocks });
    const selections: string[] = [];
    for (const [className, emitter] of emitters) {
        let selected: string | undefined;
        for (const [name, block] of Object.entries(catalog)) {
            if (block.className === className && (await block._load()) === emitter) {
                selected = name;
                break;
            }
        }
        if (!selected) {
            throw new Error(`No public block selection for "${className}"`);
        }
        selections.push(selected);
    }
    if (blocks.size !== graph.blocks.size) {
        selections.push("nodeGeometryTextureOutputBlock");
    }
    selections.sort();
    const code = [
        "// Generated by scripts/generate-node-material-loader.mts. Regenerate when graph block types change.",
        `import { createNodeMaterialBlockLoader, ${selections.join(", ")} } from ${JSON.stringify(packageName)};`,
        "",
        "export function createBlockLoader() {",
        `    return createNodeMaterialBlockLoader([${selections.join(", ")}]);`,
        "}",
        "",
    ].join("\n");
    return format(code, { ...(await resolveConfig(fileURLToPath(import.meta.url))), parser: "typescript" });
}

async function main(): Promise<void> {
    const { values } = parseArgs({
        options: {
            json: { type: "string" },
            module: { type: "string" },
            export: { type: "string" },
            property: { type: "string" },
            output: { type: "string" },
            package: { type: "string", default: "@babylonjs/lite" },
            check: { type: "boolean", default: false },
            force: { type: "boolean", default: false },
        },
    });
    if (!values.output || !!values.json === !!values.module || (values.module && !values.export)) {
        throw new Error("Usage: --json graph.json OR --module graph.ts --export name; --output loader.ts [--package @babylonjs/lite]");
    }
    if (values.check && values.force) {
        throw new Error("--check and --force cannot be combined");
    }
    if (isIgnoredScenePayloadModule(values.output)) {
        throw new Error("Generated loaders are runtime code; output must not use an excluded -nme.ts or -npe.ts payload filename");
    }
    let source: unknown;
    if (values.json) {
        source = JSON.parse(await readFile(resolve(values.json), "utf8"));
    } else {
        const module: Record<string, unknown> = await import(pathToFileURL(resolve(values.module!)).href);
        const exported = module[values.export!];
        if (exported === undefined) {
            throw new Error(`Graph export not found: ${values.export}`);
        }
        source = typeof exported === "function" ? await exported() : exported;
    }
    if (values.property) {
        if (!source || typeof source !== "object" || !Object.hasOwn(source, values.property)) {
            throw new Error(`Graph property not found: ${values.property}`);
        }
        source = (source as Record<string, unknown>)[values.property];
    }
    const code = await generateNodeMaterialLoader(source, values.package);
    if (values.check) {
        const existing = await readFile(resolve(values.output), "utf8");
        if (existing.replace(/\r\n/g, "\n") !== code.replace(/\r\n/g, "\n")) {
            throw new Error(`Generated graph loader is stale: ${values.output}`);
        }
    } else {
        await writeFile(resolve(values.output), code, { flag: values.force ? "w" : "wx" });
    }
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
    main().catch((error: unknown) => {
        console.error(error);
        process.exitCode = 1;
    });
}
