import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { format, resolveConfig } from "prettier";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const nodeDirectory = resolve(root, "packages/babylon-lite/src/material/node");
const entries = new Map<string, string>();
const registryKeys = new Set<string>();
for (const name of ["node-registry", "node-registry-extra-math", "node-registry-extra-procedural", "node-registry-extra-advanced", "node-registry-extra-compat"]) {
    const file = resolve(nodeDirectory, name + ".ts");
    const source = ts.createSourceFile(file, readFileSync(file, "utf8"), ts.ScriptTarget.Latest, true);
    const helpers = new Map<string, ts.Block>();
    for (const statement of source.statements) {
        if (ts.isFunctionDeclaration(statement) && statement.name && statement.body) {
            helpers.set(statement.name.text, statement.body);
        }
    }
    const visit = (node: ts.Node): void => {
        if (ts.isCaseBlock(node)) {
            let keys: string[] = [];
            for (const clause of node.clauses) {
                if (ts.isCaseClause(clause)) {
                    if (!ts.isStringLiteral(clause.expression)) {
                        throw new Error(`Non-literal node registry case in ${file}`);
                    }
                    keys.push(clause.expression.text);
                    registryKeys.add(clause.expression.text);
                }
                if (!keys.length || !clause.statements.length) {
                    continue;
                }
                const imports = new Set<string>();
                const resolving = new Set<string>();
                const findImport = (child: ts.Node): void => {
                    if (ts.isCallExpression(child) && child.expression.kind === ts.SyntaxKind.ImportKeyword) {
                        const specifier = child.arguments[0];
                        if (specifier && ts.isStringLiteral(specifier)) {
                            imports.add(specifier.text);
                        }
                    }
                    if (ts.isReturnStatement(child) && child.expression && ts.isIdentifier(child.expression)) {
                        const name = child.expression.text;
                        const helper = helpers.get(name);
                        if (!helper || resolving.has(name)) {
                            throw new Error(`Unresolvable node registry helper "${name}" in ${file}`);
                        }
                        resolving.add(name);
                        findImport(helper);
                        resolving.delete(name);
                    }
                    ts.forEachChild(child, findImport);
                };
                clause.statements.forEach(findImport);
                if (imports.size !== 1) {
                    throw new Error(`Expected one lazy import for ${keys.join(", ")} in ${file}`);
                }
                const specifier = [...imports][0]!;
                if (specifier.startsWith("./blocks/")) {
                    for (const key of keys) {
                        if (entries.has(key)) {
                            throw new Error(`Duplicate node registry entry: ${key}`);
                        }
                        entries.set(key, specifier);
                    }
                } else if (!specifier.startsWith("./node-registry-extra-")) {
                    throw new Error(`Unsupported node registry import "${specifier}" in ${file}`);
                }
                keys = [];
            }
        }
        ts.forEachChild(node, visit);
    };
    visit(source);
}
for (const key of registryKeys) {
    if (!entries.has(key)) {
        throw new Error(`Missing node block implementation for registry case "${key}"`);
    }
}
entries.set("GeometryTextureOutputBlock", "./blocks/geometry-texture-output.js");

function exportName(key: string): string {
    return (
        "node" +
        key
            .replace(/^NodeMaterial/, "")
            .replace(/^PBR/, "Pbr")
            .replace(/__full$/, "Full")
    );
}

const sorted = [...entries].sort(([a], [b]) => a.localeCompare(b, "en"));
const catalog = [
    "// Generated by scripts/generate-node-block-catalog.ts. Do not edit manually.",
    'import type { NodeMaterialBlock } from "./node-block-loader.js";',
    "",
    ...sorted.map(([key, specifier]) => {
        const name = exportName(key);
        const className = key.replace(/__full$/, "");
        return `/** Lazily loaded ${key} implementation. */\nexport const ${name}: NodeMaterialBlock = { className: ${JSON.stringify(className)}, _load: async () => (await import(${JSON.stringify(specifier)})).emitter };`;
    }),
    "",
].join("\n");
const indexPath = resolve(root, "packages/babylon-lite/src/index.ts");
const index = readFileSync(indexPath, "utf8");
const startMarker = "// BEGIN GENERATED NODE BLOCK EXPORTS";
const endMarker = "// END GENERATED NODE BLOCK EXPORTS";
const start = index.indexOf(startMarker);
const end = index.indexOf(endMarker);
if (start < 0 || end < start) {
    throw new Error("Node block export markers are missing from index.ts");
}
const exports = `${startMarker}\nexport {\n${sorted.map(([key]) => `    ${exportName(key)},`).join("\n")}\n} from "./material/node/node-blocks.js";\n`;
const updatedIndex = index.slice(0, start) + exports + index.slice(end);
const check = process.argv.includes("--check");
async function publish(): Promise<void> {
    const config = await resolveConfig(indexPath);
    const outputs: readonly (readonly [string, string])[] = [
        [resolve(nodeDirectory, "node-blocks.ts"), catalog],
        [indexPath, updatedIndex],
    ];
    for (const [path, content] of outputs) {
        const formatted = await format(content, { ...config, parser: "typescript" });
        if (check) {
            if (readFileSync(path, "utf8").replace(/\r\n/g, "\n") !== formatted.replace(/\r\n/g, "\n")) {
                throw new Error(`Generated node block catalog is stale: ${path}`);
            }
        } else {
            writeFileSync(path, formatted);
        }
    }
}
publish().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
});
